### ISSUE TITLE
Require example

### ISSUE THREAD

**Issue by orangeagain** [vicfergar/XAtlasSharp#2]
I am confuse to export mesh.
If you have a c# example,that will be better.
thanks a lot.

**Comment by vicfergar** [comment]
Hi @orangeagain, you are right an example project is needed. I will try to port the native one to C# and include it.

Thanks for the feedback!

**Comment by orangeagain** [comment]
here are unity c# example [xatlaskib](https://github.com/guycalledfrank/xatlasLib), but without some parameters.

**Comment by vicfergar** [comment]
Hi @orangeagain I have ported part of the original example from xatlas.

Only generation is done, no output meshes or images are exported at the moment. Hope it will be usefull for you!

**Comment by orangeagain** [comment]
> Hi @orangeagain I have ported part of the original example from xatlas.
> 
> Only generation is done, no output meshes or images are exported at the moment. Hope it will be usefull for you!

Thank you for your work. I know how to generate mesh. the difficult for me is out put mesh.
I found the solution is xatlaslib.thank both your wok.
